Add check of required arguments

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,6 +18,11 @@ while getopts "r:" opt; do
     esac
 done
 
+if [ -z "$chosen_router" ]; then
+    echo "Missing required argument '-r'" >&2
+    exit 1
+fi
+
 if [ -z "$AUTH_SEND_OPTION" ]; then
     echo "\$AUTH_SEND_OPTION is empty. Use https://jsfiddle.net/kgersen/3mnsc6wy/ to generate a token, and set it with \`export AUTH_SEND_OPTION=<result value>\`"
     exit 2
